- hosts: all
  become: true
  become_method: su
  become_user: root

  vars_prompt:
    - name: username
      prompt: what is your username?
      private: false

    - name: user_password
      prompt: what is your password?
      private: true
      encrypt: sha512_crypt
      confirm: true

  vars:
    public_keys:
      - files/id_rsa.pub

  roles:
    - create-user